ecmwf-ifs/ectrans

src/programs/ectrans-benchmark.F90

CPU runs are currently running *without* FFTW

Bug-fix in ectrans-benchmark.F90

---

src/programs/ectrans-benchmark.F90

I had a case at TCO7999 where the default behaviour of setting NPRTRV and NPRTRW didn't work. In this case it's useful to override this behaviour and force the parameters yourself, so I've added them as command line arguments. You can provide just one of the two, in which case the existing logic will determine the other by dividing NPROC by the provided value. It will also make sure the product of the two equals NPROC.
I've also included a commit which moves all default option values from `get_command_line_arguments` to the top of the program, for consistency,

Introduce V-W set specification as command line arguments in benchmark

---

src/programs/ectrans-benchmark.F90
tests/CMakeLists.txt

This PR is intended to be a discussion area for a "correctness checker", which checks that fields are being transformed back and forth correctly. This should be implemented by comparing the fields in spectral space after one or more transform cycles with the initial condition and verifying that they match to some tolerance. They won't be identical due to unavoidable rounding errors, but should roughly match to the machine epsilon.
The correctness checker is activated by passing `--check` to the benchmark code. It can be run manually or through the standard CTest command.

Implement correctness checker

---

src/programs/ectrans-benchmark.F90

How did this go undetected so long??
Fixes #26.

Fix divide-by-zero error when non-main ranks perform norm calculations

---

src/programs/ectrans-benchmark.F90

Previously only the root rank stopped, which I don't think was raceproof.

Have all ranks error stop on failed correctness check

---

src/programs/ectrans-benchmark.F90

This confused me when reading it. This value is never accessed so we don't need it.

Remove superfluous extra element of numll

---

README.md
src/programs/CMakeLists.txt
src/programs/ectrans-benchmark.F90
tests/CMakeLists.txt

I have renamed the "default" benchmark to have "cpu" in the name. I also added preprocessing so the help message correctly reports the name of the program.

Make benchmark program name clearer

---

src/programs/ectrans-benchmark-ifs.F90
src/programs/ectrans-benchmark.F90

The calculation of the ordering of fields in `zgmv` is incorrect. First spotted by @marsdeno when he tried running with `--uvders --scders --vordiv` all enabled (I had never thought of testing all three at once!). The benchmark crashed with a "partially present on device" error referring to `PGP3A`.
UV-like fields and other 3D fields are both stored in the same array: `zgmv`. `zgpuv` and `zgp3a` are pointers pointing to different slices of this array, and these are subsequently passed to `inv_trans` and `dir_trans`:
```
zgpuv => zgmv(:,:,1:jend_vder_EW,:)
zgp3a => zgmv(:,:,jbegin_sc:jend_scder_EW,:)
```
([Here](https://github.com/ecmwf-ifs/ectrans/blob/redgreengpu/src/programs/ectrans-benchmark.F90#L528C1-L530C22))
Without this fix (assuming `nfld == 1`):
`jend_vder_EW` = 6, `jbegin_sc` = …

Fix typo in ordering of fields in ZGMV

---

src/transi/CMakeLists.txt

Addresses https://github.com/ecmwf-ifs/ectrans/issues/68.  Instead of copying the symbolic links it copies the original files that the links point to in the repository.  This results in real files in the install directory.

Copy original files instead of symbolic link.

---

src/programs/ectrans-benchmark.F90

Addresses https://github.com/ecmwf-ifs/ectrans/issues/81.  I think "l1" is the standardly correct format.

Fix format.

---

src/programs/ectrans-benchmark.F90

This variable serves no purpose. It is supposed to replicate the process for initialising `NPRTRW` and `NPRTRV` in the IFS (`SUMPINI`). There one can specify in the IFS namelist a maximum allowed value for `NPRTRW`, though I'm not sure the reason you would need this. In ecTrans we don't need this feature, so it's best to just delete this.
This PR was prompted by Lucian Anton at ECMWF trying to run ecTrans on 8000 tasks without specifying `--nprtrw` and `--nprtrv`. The automatic logic does not allow running with so many tasks due to the check on `nspecresmin`.

Remove nspecresmin

---

src/programs/ectrans-benchmark.F90

Previously we completely ignored zmaxerr(4)!
Thanks @antoine-morvan for spotting this.

Fix bug in zmaxerrg calculation

---

src/programs/ectrans-benchmark.F90
src/trans/external/setup_trans0.F90
src/trans/include/ectrans/setup_trans0.h
src/trans/internal/tpm_distr.F90

Remove NCOMBFLEN parameter

---

src/trans/gpu/external/setup_trans0.F90
src/trans/gpu/internal/tpm_distr.F90

We deprecated this for CPU, so we need to deprecate for GPU too.

Deprecate COMBFLEN also for GPU

---

.github/workflows/build.yml
src/programs/ectrans-benchmark.F90

*Allows choosing between heap and stack for ZCOMBUF arrays in GTOL and LTOG transposition routines on the CPU. Silently ignored on the GPU.

Allow NOPT_MEMORY_TR to be controlled by driver command-line option.

---

src/trans/gpu/external/setup_trans0.F90

We are checking preprocessor macro USE_3XTF32 instead of USE_CUTLASS_3XTF32

Printing bug in setup_trans0

---

src/trans/gpu/CMakeLists.txt

I suggest that we remove pinned flags from setup_trans, mainly because there are no allocations in setup_trans anymore that are in the critical path.
The pinned flag used to be here for a few intermediate buffers that were copied forth and back in each iteration. Those are now gone.
If we are not removing pinned, we have to add it to a few more files to make sure we use the same API for deallocation. This is one of the reasons trans_release/trans_end is not working right now, and the error messages are far from intuitive.

No pinned flags in setup_trans

---

src/programs/ectrans-benchmark.F90

We collect `iters+2` statistics, but use `iters` to calculate the average. We should use `iters+2` to calculate the average.

Fix calculation of zstepavg

---

src/programs/ectrans-benchmark.F90
src/trans/gpu/internal/ledir_mod.F90
src/trans/gpu/internal/leinv_mod.F90

This PR should not be as difficult to review and includes:
- Add command line argument --niter-warmup to ectrans-benchmark
- Modify default to 3 as after this, experimentally the timings stay more or less constant
- Some cosmetics in printing and removal of spurious prints.

Configurable warmup iterations for ectrans-benchmark

---

CMakeLists.txt
README.md
src/trans/gpu/CMakeLists.txt
src/trans/gpu/algor/hicfft.hip.cpp
src/trans/gpu/external/setup_trans.F90

This PR is adding an implementation to call FFT functionality without Graphs, especially for debugging purposes.
This is adding a new option 
GPU_GRAPHS_FFT
similar to the GEMM and also an implementation similar to the one in FFT.
Also, I redo clang-format (with the default settings), maybe we can also just provide a clang-format file?

Add FFT implementation without graphs

---

CMakeLists.txt
tests/CMakeLists.txt

Two small CMake fixes:
- Use the Fortran linker for ectrans_test_setup_trans0
- Only apply the OpenACC search workaround for CMake < 3.25 if the corresponding option has been requested.

CMake fixes for test linker and OpenACC search

---

src/trans/gpu/algor/external/fourier/hicfft_hip.h
src/trans/gpu/algor/module/hicblas_hip.h
src/trans/gpu/algor/module/rocblasDgemmBatched.hip.cpp
src/trans/gpu/algor/module/rocblasSgemmBatched.hip.cpp

Tried to compile on LUMI and saw that the HIP paths have changed for ROCm 6.
There is already a pull request for the develop branch, but not for the redgreengpu branch, so I created one.
Tested on LUMI using the following modules:
```bash
module load LUMI/24.03 partition/G cpe/24.03 PrgEnv-cray/8.5.0  \
craype-x86-trento craype-accel-amd-gfx90a rocm/6.0.3 \
cray-fftw/3.3.10.7 cray-libsci/24.03.0 buildtools/24.03
```

[redgreengpu] Fixed HIP include paths to support ROCm/6.0.3 on LUMI

---

src/trans/gpu/algor/hicblas_hip.h
src/trans/gpu/algor/hicfft_hip.h

Thanks to Paul for pointing this out.
Note that this will probably break support for < ROCm 6. Do we need to add preprocessor guards to choose the correct include for < ROCm 6? We might still need to support that on LUMI-G.

Update paths to HIP includes to support ROCm >= 6

---

src/trans/common/internal/tpm_gen.F90

These gave the impression that TPM_GEN is the appropriate place to change the default values of these variables. This is not the case, because whatever value they take here is overwritten in SETUP_TRANS0. The latter is where default values should be set.

Remove default values for TPM_GEN variables

---

src/trans/gpu/internal/trgtol_mod.F90
src/trans/gpu/internal/trltog_mod.F90
src/trans/gpu/internal/trltom_mod.F90
src/trans/gpu/internal/trmtol_mod.F90

Finally, we are able to run the develop branch on AMD GPUs.
Many many thanks to @PaulMullowney for getting this done.
Note that #155 should be merged first.

Add support for AMD GPUs

---

src/trans/gpu/algor/hicblas_gemm.hip.cpp

We were missing two calls to `HICBLAS_CHECK`.

Adding missing blas runtime checks

---

src/trans/cpu/CMakeLists.txt
src/trans/gpu/CMakeLists.txt

```
gmake[2]: *** No rule to make target '..../src/trans/gpu/internal/.fsc_mod.F90.swp', needed by 'src/trans/gpu/generated/ectrans_gpu_sp/internal/.fsc_mod.F90.swp'.  Stop.
gmake[1]: *** [CMakeFiles/Makefile2:1020: src/trans/gpu/CMakeFiles/ectrans_gpu_sp.dir/all] Error 2
```
I have encountered this error message numerous times, and today was the tipping point, so I finally went ahead and create a proper fix. I hope I haven't missed more places with very generic patterns.

fix glob pattern

---

.github/workflows/build-hpc.yml
CMakeLists.txt
src/trans/gpu/CMakeLists.txt
tests/CMakeLists.txt

This PR tidies up the testing structure and adds tests for the GPU version.
I had to undo PR #158 as it causes a crash on our system: `invalid device buffer`.
I also had to disable the `--nfld 0` test as this fails on GPU.
This PR builds on #175.

Add GPU tests

---

src/trans/gpu/external/setup_trans.F90

For large problems e.g. TCO2559, the sizes (in bytes) of arrays `FG%ZAA` and `FG%ZAS` can be reported as negative in `SETUP_TRANS`. This is because the `SIZE` function returns a 4-byte signed integer value, maximum about 2 billion, by default. For certain configurations the sizes of `ZAS` and `ZAA` (in number of elements) can go above this value, leading to an integer overflow. This number is then multiplied by the result of `C_SIZEOF` which I think returns a `C_SIZE_T`. It seems that the result of this product between two different integer types is an 8-byte integer, for some reason.
This PR fixes this bug by requesting a wider integer value from the `SIZE` function.
Write a simple program that only does a setup:
```fortran
PROGRAM TEST_PROGRAM
USE PARKIND1, ONLY: JPIM, JPRB
USE …
```

Fix overflow bug in printing of Legendre polynomial arrays

---

src/trans/gpu/internal/trgtol_mod.F90

This is a very minor PR correcting an OMP directive when building ECTrans without MPI, for PR #211
I used the test program from @samhatfield's comment [here](https://github.com/ecmwf-ifs/ectrans/pull/211#issuecomment-2648227585) to verify the OMP implementation on the GPU on MI300A with and without unified memory enabled. I am getting identical results in both cases!
Here are the results running on MI300A in "discrete GPU" mode (HSA_XNACK=0):
single precision:
```
ecTrans at version: 1.5.1
commit: 59c7ff9739dac8e1332f7c788dbbe3f67a929eb1
R%NTMAX= 79
R%NSMAX= 79
setup_trans: sizes1 NUMP= 80
Using OpenMP offloading
FG%ZAS:       611840B
FG%ZAA:       611840B
FG%ZAS0:        26240B
FG%ZAA0:        25600B
FG%ZEPSNM:        26240B
===GPU arrays successfully allocated
GRID_POINT_FIELD = …
```

Fix omp update directive in trgtol_mod (no MPI code path)

---

cmake/ectrans_compile_options.cmake

Improves the CMake logic that identifies `gfortran` versions that have trouble compiling the `CONTIGUOUS` keyword. 
Please see https://github.com/ecmwf-ifs/ectrans/issues/216 for details and discussion.

Flag more versions of gfortran as having issue with CONTIGUOUS

---

src/programs/ectrans-benchmark.F90

This is needed so that device-side arrays are correctly deallocated at the end (especially important for CCE builds).

Add trans_end statement in ectrans benchmark program

---

.github/workflows/build-hpc.yml

On LUMI-G, actions currently take place in the following directory:
```
/scratch/{project}/github-actions/ectrans/{pipeline ID}
```
There is no qualification for repeated runs of the same action, e.g. if the action fails and needs to be repeated. This means the repeated action fails because it assumes it's running in a clean directory. See e.g. [this action](https://github.com/ecmwf-ifs/ectrans/actions/runs/14265546118/job/40086431362?pr=249):
```
/scratch/***/github-actions/ectrans/14265546118/ecmwf/ecbuild /scratch/***/github-actions/ectrans/14265546118
+ git init
Reinitialized existing Git repository in /pfs/lustrep4/scratch/***/github-actions/ectrans/14265546118/ecmwf/ecbuild/.git/
+ git remote add origin https://github.com/ecmwf/ecbuild
error: remote origin already exists.
```
This …

Properly qualify work and output dirs for repeated actions

---

CMakeLists.txt
tests/CMakeLists.txt

If possible, MPI should not be a requirement for the TESTS feature. At the moment we can't build ecTrans with amdflang and MPI (at least not with OpenMPI). For now we will disable MPI in the CI when building with amdflang. We still want to run the remaining serial test suite when building with amdflang though.

MPI-free testing

---

.github/workflows/build-hpc.yml

Just for LUMI, this builds with only 1 thread, and doesn't use ninja.
- Using 1 thread because there seems to try to avoid an OpenACC compilation error:
```
prfi1b_mod.F90-pp_1.acc.o: No such file or directory
ftn-7932 ftn: ERROR in command line
Error generating accelerator code: offload bundling failure
```
- Not using ninja because using ninja leads to many warnings of the Cray compiler:
`The lister is using the source file "xxx.F90", rather than the specified source file "xxx.F90-pp.f90"`

GHA build-hpc: On LUMI, build with 1 task, and do not use ninja

---

src/programs/ectrans-benchmark.F90
tests/CMakeLists.txt

INV_TRANS and DIR_TRANS support two ways of passing arrays:
1) PSPVOR, PSPDIV, PSPSCALAR <=> PGP
2) PSPVOR, PSPDIV <=> PGPUV; PSPSC3A <=> PGP3A; PSPSC2 <=> PGP2
Previously we only supported the second one. With this commit you can now also call the first style. In the IFS we use both cases in different places so it's important to have both cases covered.
We can now extend the test suite so more of the code has coverage.
I am still trying to figure out how scalar fields are packed, hence this branch gives erroneous norms for scalar fields. I will continue working on this.

Add ability to call ecTrans with two "call modes" in benchmark

---

tests/CMakeLists.txt

Currently there are 530 tests executed for the GPU CI actions which is starting to reach the reasonable limit in terms of the job wall time on the HPC systems these actions run on. Here is the breakdown for the 530 tests:
- 1: ectrans_test_install
- 3: ectrans_test_setup_trans0
- 6: ectrans_test_adjoint
- 12: ectrans_test_{dir/inv}trans_adjoint
- 6: ectrans_test_gpnorm_trans_adjoint
- 288: benchmark tests (CPU)
- 72: benchmark tests (GPU)
- 126: LAM benchmark tests (CPU)
- 16: transi tests
The big one is the CPU benchmark tests. For each precision in "dp sp", for each ntasks in "0 1 2", for each nthreads in "1 4 8", and for each callmode in "1 2", we execute the following:
- benchmark with nfld 0
- benchmark with nfld 10
- benchmark with nfld 10 and nlev 20
- benchmark with nfld10, nlev …

Reduce test set size
